name: snakepop
channels:
  - conda-forge
  - bioconda

dependencies:
  - python=3.11

  # workflow
  - snakemake

  # alignment / variant calling
  - bwa
  - samtools
  - bcftools
  - htslib
  - pysam
  - bedtools
  - tabix

  # core python
  - numpy<2
  - pandas
  - scipy
  - matplotlib
  - pyyaml

  # PCA / plotting
  - plink
  - plink2
  - plotly
  - python-kaleido

  # population genomics
  - vcftools
  - scikit-allel
  - dask
  
  # tree
  - iqtree
  - ete3
  - astral-tree
  - seqkit
  - biopython
